name: Python Flask Docker

on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: self-hosted  # or use 'ubuntu-latest' if not using a self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t secondimage .
      - name: Run the docker image
        run: docker run -d -p secondimage
