name: Python Flask Docker

on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t testimage .
   cluster-login:
    
